name: kvk_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ^1.17.5

dependencies:
  flutter:
    sdk: flutter
  

  ## Database connection
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.1

  firebase_messaging: ^7.0.3

  #Firebase Storage Package to store Images and Files etc
  firebase_storage: ^4.0.0

  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.18.0+1
  
  #State management
  stacked: ^1.2.2

  #Swipe up bar
  sliding_up_panel: ^1.0.2

  #Screen pathing optimisation
  auto_route: 0.6.7

  #Service Manager
  stacked_services:

  #Allow for adding images
  image_picker: ^0.6.6+5

  #Attaching Files
  file_picker: ^2.0.11

  #Displaying Videos
  video_player: 0.11.0

  #Allow for single run methods in Future builder
  async: ^2.4.1

  get_it:

  #Alerts
  rflutter_alert: ^1.0.3

  #Updating two view models based on changes to one service
  observable_ish:
  
  flutter_hooks:
  stacked_hooks: ^0.1.1+3

  #Generates locator code for services and classes through annotation
  injectable:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  #Open Phone App and download files
  url_launcher: ^5.7.6

  #bottom nav post button for admin
  flutter_fab_dialer: ^0.1.1

  scrollable_positioned_list: ^0.1.8

  
  logger: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator:
  injectable_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/gifs/kvk_loading_one.gif
    - assets/img/blank_profile.png
    - assets/img/icar_logo.png
    - assets/img/svm_logo.png
    - assets/img/pdf_icon.png
    - assets/img/doc_icon.png
    - assets/img/excel_icon.png
    - assets/img/ppt_icon.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Leaf
      fonts:
        - asset: fonts/leaf_font.ttf
    - family: kvkIcons
      fonts:
        - asset: icons/kvk_icons.ttf
